name: Deploy DB (main)

on:
  push:
    branches: ['main']
    paths:
      - 'supabase/**'
      - '.github/workflows/db-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          # Download and install the latest Supabase CLI binary
          wget -qO supabase.tar.gz https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz
          tar -xzf supabase.tar.gz
          sudo mv supabase /usr/local/bin/supabase
          sudo chmod +x /usr/local/bin/supabase
          supabase --version

      # Authenticate the CLI with a personal access token (scoped minimal)
      - name: Link to project
        run: supabase link --project-ref ${{ secrets.SB_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SB_ACCESS_TOKEN }}

      - name: Push migrations to remote
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SB_ACCESS_TOKEN }}
